version: '3.1'

services:
  db:
    image: postgres:11.5
    restart: always
    ports:
      - '5433:5432'
    environment:
      POSTGRES_PASSWORD: gre123
      POSTGRES_USER: greuser
      POSTGRES_DB: scratchpad_test